version: '3'
services:
  tanzu-watcher:
    image: bkurt/tanzu-install-watcher:0.1
    env_file:
    - tanzu.env
    deploy:
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 5
